import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import NavigationBar from "@/components/nav-bar";
import BottomBar from "@/components/bottom-bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Arkham Horror the Living Card Game Tracker",
  description: "Generated by Derick Hfor Arkham Horror the Living Card Game",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="font-sans flex flex-col items-center justify-items-center min-h-screen gap-4 max-w-4xl mx-auto px-2">
            <NavigationBar />
            {children}
            <BottomBar />
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
